// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/learning/radicals": {
    params: {};
  };
  "/learning/radicals/:radicalSessionId": {
    params: {
      "radicalSessionId": string;
    };
  };
  "/learning/radicals/:radicalSessionId/memorization": {
    params: {
      "radicalSessionId": string;
    };
  };
  "/learning/radicals/:radicalSessionId/test": {
    params: {
      "radicalSessionId": string;
    };
  };
  "/learning/radicals/tests/:id/result": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/learning/radicals" | "/learning/radicals/:radicalSessionId" | "/learning/radicals/:radicalSessionId/memorization" | "/learning/radicals/:radicalSessionId/test" | "/learning/radicals/tests/:id/result";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/auth/register.tsx": {
    id: "routes/auth/register";
    page: "/register";
  };
  "routes/learning/radicals.tsx": {
    id: "routes/learning/radicals";
    page: "/learning/radicals";
  };
  "routes/learning/radicals/[id]/index.tsx": {
    id: "routes/learning/radicals/[id]/index";
    page: "/learning/radicals/:radicalSessionId";
  };
  "routes/learning/radicals/[id]/memorization.tsx": {
    id: "routes/learning/radicals/[id]/memorization";
    page: "/learning/radicals/:radicalSessionId/memorization";
  };
  "routes/learning/radicals/[id]/test.tsx": {
    id: "routes/learning/radicals/[id]/test";
    page: "/learning/radicals/:radicalSessionId/test";
  };
  "routes/learning/tests/[id]/result.tsx": {
    id: "routes/learning/tests/[id]/result";
    page: "/learning/radicals/tests/:id/result";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/register": typeof import("./app/routes/auth/register.tsx");
  "routes/learning/radicals": typeof import("./app/routes/learning/radicals.tsx");
  "routes/learning/radicals/[id]/index": typeof import("./app/routes/learning/radicals/[id]/index.tsx");
  "routes/learning/radicals/[id]/memorization": typeof import("./app/routes/learning/radicals/[id]/memorization.tsx");
  "routes/learning/radicals/[id]/test": typeof import("./app/routes/learning/radicals/[id]/test.tsx");
  "routes/learning/tests/[id]/result": typeof import("./app/routes/learning/tests/[id]/result.tsx");
};