// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/learning/radicals": {
    params: {};
  };
  "/learning/frequency": {
    params: {};
  };
  "/practice/radicals": {
    params: {};
  };
  "/practice/radicals/:sessionId": {
    params: {
      "sessionId": string;
    };
  };
  "/practice/radicals/:sessionId/memorization": {
    params: {
      "sessionId": string;
    };
  };
  "/practice/radicals/assessments/:assessmentId": {
    params: {
      "assessmentId": string;
    };
  };
  "/practice/radicals/assessments/:id/result": {
    params: {
      "id": string;
    };
  };
  "/practice/sentences": {
    params: {};
  };
  "/practice/sentences/:sessionId": {
    params: {
      "sessionId": string;
    };
  };
  "/practice/sentences/:sessionId/memorization": {
    params: {
      "sessionId": string;
    };
  };
  "/practice/sentences/assessments/:assessmentId": {
    params: {
      "assessmentId": string;
    };
  };
  "/practice/sentences/assessments/:id/result": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/learning/radicals" | "/learning/frequency" | "/practice/radicals" | "/practice/radicals/:sessionId" | "/practice/radicals/:sessionId/memorization" | "/practice/radicals/assessments/:assessmentId" | "/practice/radicals/assessments/:id/result" | "/practice/sentences" | "/practice/sentences/:sessionId" | "/practice/sentences/:sessionId/memorization" | "/practice/sentences/assessments/:assessmentId" | "/practice/sentences/assessments/:id/result";
  };
  "layouts/AuthLayout.tsx": {
    id: "layouts/AuthLayout";
    page: "/login" | "/register";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/auth/register.tsx": {
    id: "routes/auth/register";
    page: "/register";
  };
  "layouts/ProtectedLayout.tsx": {
    id: "layouts/ProtectedLayout";
    page: "/" | "/learning/radicals" | "/learning/frequency" | "/practice/radicals" | "/practice/radicals/:sessionId" | "/practice/radicals/:sessionId/memorization" | "/practice/radicals/assessments/:assessmentId" | "/practice/radicals/assessments/:id/result" | "/practice/sentences" | "/practice/sentences/:sessionId" | "/practice/sentences/:sessionId/memorization" | "/practice/sentences/assessments/:assessmentId" | "/practice/sentences/assessments/:id/result";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/learning/radicals.tsx": {
    id: "routes/learning/radicals";
    page: "/learning/radicals";
  };
  "routes/learning/frequency.tsx": {
    id: "routes/learning/frequency";
    page: "/learning/frequency";
  };
  "routes/practice/radicals.tsx": {
    id: "routes/practice/radicals";
    page: "/practice/radicals";
  };
  "routes/practice/radicals/[id]/index.tsx": {
    id: "routes/practice/radicals/[id]/index";
    page: "/practice/radicals/:sessionId";
  };
  "routes/practice/radicals/[id]/memorization.tsx": {
    id: "routes/practice/radicals/[id]/memorization";
    page: "/practice/radicals/:sessionId/memorization";
  };
  "routes/practice/radicals/assessments/[id]/index.tsx": {
    id: "routes/practice/radicals/assessments/[id]/index";
    page: "/practice/radicals/assessments/:assessmentId";
  };
  "routes/practice/radicals/assessments/[id]/result.tsx": {
    id: "routes/practice/radicals/assessments/[id]/result";
    page: "/practice/radicals/assessments/:id/result";
  };
  "routes/practice/sentences.tsx": {
    id: "routes/practice/sentences";
    page: "/practice/sentences";
  };
  "routes/practice/sentences/[id]/index.tsx": {
    id: "routes/practice/sentences/[id]/index";
    page: "/practice/sentences/:sessionId";
  };
  "routes/practice/sentences/[id]/memorization.tsx": {
    id: "routes/practice/sentences/[id]/memorization";
    page: "/practice/sentences/:sessionId/memorization";
  };
  "routes/practice/sentences/assessments/[id]/index.tsx": {
    id: "routes/practice/sentences/assessments/[id]/index";
    page: "/practice/sentences/assessments/:assessmentId";
  };
  "routes/practice/sentences/assessments/[id]/result.tsx": {
    id: "routes/practice/sentences/assessments/[id]/result";
    page: "/practice/sentences/assessments/:id/result";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layouts/AuthLayout": typeof import("./app/layouts/AuthLayout.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/register": typeof import("./app/routes/auth/register.tsx");
  "layouts/ProtectedLayout": typeof import("./app/layouts/ProtectedLayout.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/learning/radicals": typeof import("./app/routes/learning/radicals.tsx");
  "routes/learning/frequency": typeof import("./app/routes/learning/frequency.tsx");
  "routes/practice/radicals": typeof import("./app/routes/practice/radicals.tsx");
  "routes/practice/radicals/[id]/index": typeof import("./app/routes/practice/radicals/[id]/index.tsx");
  "routes/practice/radicals/[id]/memorization": typeof import("./app/routes/practice/radicals/[id]/memorization.tsx");
  "routes/practice/radicals/assessments/[id]/index": typeof import("./app/routes/practice/radicals/assessments/[id]/index.tsx");
  "routes/practice/radicals/assessments/[id]/result": typeof import("./app/routes/practice/radicals/assessments/[id]/result.tsx");
  "routes/practice/sentences": typeof import("./app/routes/practice/sentences.tsx");
  "routes/practice/sentences/[id]/index": typeof import("./app/routes/practice/sentences/[id]/index.tsx");
  "routes/practice/sentences/[id]/memorization": typeof import("./app/routes/practice/sentences/[id]/memorization.tsx");
  "routes/practice/sentences/assessments/[id]/index": typeof import("./app/routes/practice/sentences/assessments/[id]/index.tsx");
  "routes/practice/sentences/assessments/[id]/result": typeof import("./app/routes/practice/sentences/assessments/[id]/result.tsx");
};